### ISSUE TITLE
Error in Ubuntu Desktop 20.04

### ISSUE THREAD

**Issue by chanharryc** [horryruo/ikoa-vps#3]
I was facing a problem on my Ubuntu 20.04

After install I run python3 start.py

Here is my return:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/ikoa-vps/wsgi.py", line 1, in <module>
    from app import APP as application
  File "/root/ikoa-vps/app.py", line 118, in <module>
    def prevent_idiling():
  File "/usr/local/lib/python3.8/dist-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/schedulers/base.py", line 466, in inner
    self.add_job(func, trigger, args, kwargs, id, name, misfire_grace_time, coalesce,
  File "/usr/local/lib/python3.8/dist-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.8/dist-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.8/dist-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/local/lib/python3.8/dist-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported

May I know is my UNIX moreutils  install properly.
Thank you in advance.

**Comment by chanh0** [comment]
i tried deploy this to two new build ubuntu 20.04 successfully with below addidional cmd  ( see below 3.1 );
you may try, hope this help . 

1、Python 3.6+ is Required

2、git clone https://github.com/horryruo/ikoa-vps.git && chmod +x ikoa-vps

3、cd ikoa-vps

3.1、sudo apt update && sudo apt upgrade && sudo apt install python3-pip && sudo apt-get install moreutils

4、pip3 install -r requirements.txt

5、cp config.ini.example config.ini

6、install rclone curl https://rclone.org/install.sh | sudo bash

**Comment by horryruo** [comment]
It seems that there is a problem with the wsgi component and flask, try `pip3 install -r requirements.txt` again. And I didn't use ubuntu much, so I didn't see other problems for the time being.

**Comment by horryruo** [comment]
> i tried deploy this to two new build ubuntu 20.04 successfully with below addidional cmd ( see below 3.1 );
> you may try, hope this help .
> 
> 1、Python 3.6+ is Required
> 
> 2、git clone https://github.com/horryruo/ikoa-vps.git && chmod +x ikoa-vps
> 
> 3、cd ikoa-vps
> 
> 3.1、sudo apt update && sudo apt upgrade && sudo apt install python3-pip && sudo apt-get install moreutils
> 
> 4、pip3 install -r requirements.txt
> 
> 5、cp config.ini.example config.ini
> 
> 6、install rclone curl https://rclone.org/install.sh | sudo bash

Upgrading the apt package is indeed an effective method

**Comment by chanharryc** [comment]
Thank you. Finally I had complete install.
